require 'rubygems'
require 'rubygems/package_task'
require 'rake/testtask'
gem 'rdoc'
require 'rdoc/rdoc'
require 'rdoc/task'

PKG_NAME = 'ntxt'
PKG_VERSION = '1.0.5'

PKG_FILES = FileList[
'README.rdoc',
'lib/**/*rb',
'bin/*'
]

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = 'A parser and some tools for the ntxt text block format.'
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.requirements = []
  s.files = PKG_FILES
  s.executables = [ 'ntxt' ]
  s.require_path = 'lib'
  s.author = 'Sam Baskinger'
  s.email = 'basking2@yahoo.com'
  s.homepage = 'http://coffeesgone.wordpress.com'
  s.description = <<EOF
A library and command line tool for parsing plain text into blocks by
indentation and a simple wiki-esque == header == notation. Tagging of blocks
and searching them is also supported.
EOF
end

Gem::PackageTask.new( spec ) do |pkg|
  pkg.need_tar_bz2 = true
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

RDoc::Task.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include( "README.rdoc", "lib/**/*.rb", "bin/*" )
  rd.options << "--all"
end

task :all => [ :test, :rdoc, :package ]
task :default => [ :test, :rdoc, :package ]
