# Copyright (C) 2014 by Sam Baskinger
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require 'rubygems'
require 'rubygems/package_task'
gem 'rdoc'
require 'rake/testtask'
require 'rdoc/rdoc'
require 'rdoc/task'

PKG_NAME    = 'ntxt'
PKG_VERSION = '1.0.8'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = 'A parser and some tools for the ntxt text block format.'
  s.name = PKG_NAME
  s.version = PKG_VERSION
  s.requirements = []
  s.files = FileList[ 'README.rdoc', 'lib/**/*rb', 'lib/ntxt/server/**', 'bin/*' ]
  s.executables = [ 'ntxt' ]
  s.require_path = 'lib'
  s.required_ruby_version = '>= 2.0.0'

  s.extra_rdoc_files = [ 'README.rdoc', 'Changelog' ]
  s.author = 'Sam Baskinger'
  s.email = 'basking2@yahoo.com'
  s.homepage = 'http://sam.baskinger.tiddlyspot.com'
  s.license = 'MIT'
  s.description = <<EOF
A library and command line tool for parsing plain text into blocks by
indentation and a simple wiki-esque == header == notation. Tagging of blocks
and searching them is also supported.
EOF
end

Gem::PackageTask.new( spec ) do |pkg|
  pkg.need_tar_bz2 = true
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/ts*.rb']
  t.verbose = true
end

RDoc::Task.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include( "README.rdoc", "lib/**/*.rb" )
  rd.options << "--all"
end

task :all => [ :test, :rdoc, :package ]
task :default => [ :test, :rdoc, :package ]
